version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.6.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - setup_remote_docker:
          docker_layer_caching: true

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
    
      # docker login
      - run: |
          docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"

      # build docker image
      - run: docker build -t abdelrhmanali/commuinty-sw2 .

      # push docker image
      - run: docker push abdelrhmanali/commuinty-sw2